### ISSUE TITLE
Add configuration settings for using the PostgreSQL database

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/django-project#10]
## Task
- [x] Add the `psycopg2-binary` package to `requirements/base.txt` dependency package list. The package is used to connect Django project with the PostgreSQL database management system.
- [x] Modify the `.env_example` file with a placeholder environmental variables for the database credentials. Add `DB_NAME`, `DB_USER`, `DB_PASSWORD` & `DB_HOST` placeholder variables.
- [x] Modify `config/settings/base.py` module to add settings for connecting to the PostgreSQL DBMS.

**Note:**: Do not delete the setting for the `sqlite3` database. Instead, comment out the setting code for any possible future use.
