### ISSUE TITLE
Replace default database with `MYSQL`

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/django-project#19]
# Goal
Currently, `PostreSQL` is used as the default database engine. This should be replaced by the `MYSQL` database engine.

## Tasks
- [x] Replace the database settings using `MYSQL` configuration values.
- [x] Install `mysqlclient` to connect the backend with the database.
- [x] Update the `env_example` and `.travis.yml` files
