### ISSUE TITLE
Move the signals to create user profile in their own file

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/django-project#21]
# Goal
Currently, when a new user instance is created/updated, an associated user profile instance is created/updated using the signals `create_user_profile` and `update_user_profile` respectively. However, these signals are currently placed in the `accounts/models.py` file. They should be moved to their own module.

## Tasks
-  [ ] Move the `create_user_profile` & `update_user_profile` signals from `accounts/models.py` to `accounts/signals.py` module.
- [ ] For the signals to be executed, import the module in `accounts/apps.py` module `ready` method.
- [ ] Write tests for the signals. The tests should be placed in `accounts/tests/test_signals.py` file.

**Comment by eyobofficial** [comment]
Functionalities in this issue have been implemented in PR #29.
